FROM node:23-alpine AS build

ARG APP_DEBUG
ARG APP_VERSION
ARG APP_NAME
ARG APP_DESCRIPTION
ARG APP_BASE_URL
ARG APP_WS_URL
ARG SUPERSET_BASE_URL
ARG SUPERSET_EMBED_ADMIN_ID

ENV APP_DEBUG=$APP_DEBUG
ENV APP_VERSION=$APP_VERSION
ENV APP_NAME=$APP_NAME
ENV APP_DESCRIPTION=$APP_DESCRIPTION
ENV APP_BASE_URL=$APP_BASE_URL
ENV APP_WS_URL=$APP_WS_URL
ENV SUPERSET_BASE_URL=$SUPERSET_BASE_URL
ENV SUPERSET_EMBED_ADMIN_ID=$SUPERSET_EMBED_ADMIN_ID

WORKDIR /app
RUN npm install -g @angular/cli

COPY ./package.json .
RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build-deploy --configuration=production

FROM nginx:alpine AS runtime
EXPOSE 80
COPY --from=build /app/dist /usr/share/nginx/html