name: Build and Deploy develop
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Deploy develop
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Notify Discord (Build Started)
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot GitHub", "content": "🚀 **Build iniciado!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nBranch: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }} || true

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.x'

    - name: Install dependencies
      run: npm install --force

    - name: Prebuild Angular App
      run: npm run build-prod
      env:
        APP_DEBUG: production
        APP_VERSION: ${{ github.ref_name }} 
        APP_NAME: ${{ github.repository }}
        APP_DESCRIPTION: Description
        APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
        APP_WS_URL: ${{ secrets.APP_WS_URL }}
        SUPERSET_BASE_URL: ${{ secrets.SUPERSET_BASE_URL }}
        SUPERSET_EMBED_ADMIN_ID: ${{ secrets.SUPERSET_EMBED_ADMIN_ID }}
  
    - name: Build Angular App
      run: npm run build -- --output-path=dist --base-href /chat-web/ --configuration=production

    - name: Install Github Pages
      run: npm i -g angular-cli-ghpages

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist
        token: ${{ secrets.GH_TOKEN }}

  report-status:
    name: Report Build Status
    needs: build
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Notify Discord (Success)
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot Github", "content": "✅ **Sucesso ao gerar versão!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nBranch: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord (Failure)
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot Github", "content": "❌ **Falha ao gerar versão!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nBranch: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}